# Generated by Django 3.2 on 2024-02-09 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BSApp', '0002_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='eage',
            new_name='esal',
        ),
    ]
